### ISSUE TITLE
freppledata is messed up for 16.0

### ISSUE THREAD

**Issue by etoimene** [frePPLe/odoo#12]
I had to manually activate subcontracting, workorders, contacts
res.partners model demo data is missing but it is referenced in other demo data ...

That is how far I got and gave up.

Module is good idea to help potential customers up to speed but not very usable at the moment.

If I catch some time, I'll try to fix it.

**Comment by jdetaeye** [comment]
We're using the freppledata to populate https://odoo16.frepple.com/, and it's also used for our unit tests.   

This python script https://github.com/frePPLe/frepple/blob/master/freppledb/odoo/management/commands/odoo_container.py is used to start up an odoocontainer and link it to a frepple instance.
The dockerfile we use for odoo is here https://github.com/frePPLe/odoo/blob/16.0/dockerfile

Any pull request you submit to "fix it" will need to be compatible with the above...

**Comment by etoimene** [comment]
Oh, I assumed I could use it to populate Odoo instance created by installation of frepple module.

Nothing to fix here. Closing the issue.
