### ISSUE TITLE
Only aggregate forecast method selectable.

### ISSUE THREAD

**Issue by wlin-kencove** [frePPLe/odoo#15]
This might be more of a configuration issue. We wanted to see the forecast when run with different methods but only see the aggregate method.

<img width="545" alt="image" src="https://github.com/user-attachments/assets/6ee8cc88-5e9c-4459-abbc-0a3bf6b9bd28">

We are unable to select a different method. Is there a setting that allows selection of the other methods?

**Comment by jdetaeye** [comment]
Check out https://frepple.com/docs/current/examples/forecasting/middle-out-forecast.php  and the online example model https://demo.frepple.com/middle-out-forecast/forecast/editor/

The key configuration step is to add records in the forecast table for the groups.   If these records are not there, then the higher level will only have "aggregate" as an option.
![image](https://github.com/user-attachments/assets/4aac3790-4c4c-4b22-8f6a-2d0ad8667327)

**Comment by wlin-kencove** [comment]
Thanks for the quick response. I will give that a try
