### ISSUE TITLE
Error installing module 

### ISSUE THREAD

**Issue by woutswennen** [frePPLe/odoo#16]
In sale_views.xml you are using xpath to place the Quote button after commitment _date_div
`<xpath expr="//div[@name='commitment_date_div']" position="after">`

The problem occurs when you also install the sale_stock module (standard odoo)
In there they replace the commitment_date_div 
`<xpath expr="//div[@name='commitment_date_div']" position="replace">`

Would it be possible to fix this by using the sale_shipping group for the xpath reference?
Thanks in advance

**Comment by jdetaeye** [comment]
Yes, will replace it.    We have seen issue with the installation and differences between enterprise and community versions of odoo.   But we hadn't traced the issues back yet to the sale_stock module.

As a temporary workaround you can also comment out "sales_view.xml" from your manifiest. The quoting button isn't a critical feature for the majority of users.

**Comment by jdetaeye** [comment]
Fixed in 3e4e1f04580227f27e9d8729cd2b89aabfd43a3b
