### ISSUE TITLE
failed connection to Odoo

### ISSUE THREAD

**Issue by overthrowrobotics** [frePPLe/odoo#3]
frePPLe 6.10, Odoo 13. Both fresh installs. The instructions are unclear as to where we configure the odoo parameters on the frePPLe side but I did it under Admin/Parameters. When I run http://192.168.86.39/frepple/xml?database=test2&company=companyName I get an internal server error and it says to check Odoo log. 

Odoo log shows: ValueError: Invalid field 'requested_date' on model 'sale.order'
I don't see in the frePPLe Odoo module any reference to adding requested_date to sale.order in the models folder. It's not in the standard Odoo database so there must be some other unreferenced Odoo module that needs to be added. Searching Google for any module with requested_date in sale.order returns nothing. So complete mystery. 

In Odoo under Manufacturing, Advanced planning - frePPLe I see 192.168.86.23 refused connection. When I get the URL from Inspect in the browser I am able to open it ok in another tab, not sure why it doesn't show up here.

**Comment by jdetaeye** [comment]
>Odoo log shows: ValueError: Invalid field 'requested_date' on model 'sale.order'

No worries on that one.  It's a non-fatal warning.

>In Odoo under Manufacturing, Advanced planning - frePPLe I see 192.168.86.23 refused connection. When I get the URL from Inspect in the browser I am able to open it ok in another tab, not sure why it doesn't show up here.

Looks like an Xframe permission issue. By default we don't allow embedding frepple content in an iframe for security reasons.
Make sure to check out these points from the configuration instructions on https://frepple.org/docs/current/integration-guide/odoo-connector.php :
- Make sure the setting MIDDLEWARE doesn’t include the “django.middleware.clickjacking.XFrameOptionsMiddleware” class.
- Add a line “SESSION_COOKIE_SAMESITE = None”

Also, this type of questions doesn't belong here as an issue.  Post a message to the user forum instead.

**Comment by jdetaeye** [comment]
Also make sure to have this odoo config correct:
>FrePPLe needs to be loaded as a server wide module. This is achieved by updating an option in the Odoo configuration file: “server_wide_modules= frepple,web,web_kanban”

**Comment by overthrowrobotics** [comment]
The server_wide_modules is in odoo config file. I also followed the following. The django.middleware part want in there. 
Make sure the setting MIDDLEWARE doesn’t include the “django.middleware.clickjacking.XFrameOptionsMiddleware” class.
Add a line “SESSION_COOKIE_SAMESITE = None”

I'll post in the user forum too. I'm still confused by the expected_date because I can't find that referenced in code anywhere. Should I just add it to the Odoo module and then do a PR?

**Comment by overthrowrobotics** [comment]
One more thing. Is the user group on Google Groups? I signed up but there is no way to make a post and I didn't receive any kind of verification email. Do I just wait for someone to manually verify me, it's not clear.

**Comment by jdetaeye** [comment]
Closing after inactivity
