### ISSUE TITLE
Import data from Odoo status sitting at 0%

### ISSUE THREAD

**Issue by JevinD** [frePPLe/odoo#9]
Background:
I have a frePPLe system and an Odoo system that I am able to get a successful task completion when I launch the "Import data from odoo" with a simple Odoo database with a few records for Sale Orders and Manufacturing Orders.

Issue: 
When I configure this to an Odoo database containing production data, the frePPle status sits at 0% with the logs showing this.

Start logging frePPLe 6.20.1 (Feb 11 2022) at 2022-03-10T18:48:04
FrePPLe on linux using database 'default'
INFO Start step 70 'Load Odoo data' at 18:48:04

On the Odoo logging I see the frepple user logging in successfully and then no information about what it is doing.

Expected Result: 
On the frePPLe system I would expect to see the status say done and for the Odoo data to be imported in to frePPLe.

Are there any ideas on what may be happening here?

**Comment by JevinD** [comment]
@max3903

**Comment by jdetaeye** [comment]
Closing old inactive issue.
